In [2]:
#Activity_1(a)
# Simple calculator program to include additional operations: subtraction, multiply, modulus (%), exponentiation (), and floor division (//).
def calculator():
    print("Select operation:")
    print("1. Addition (+)")
    print("2. Subtraction (-)")
    print("3. Multiplication (*)")
    print("4. Division (/)")
    print("5. Modulus (%)")
    print("6. Exponentiation (**)")
    print("7. Floor Division (//)")

    choice = input("Enter choice (1/2/3/4/5/6/7): ")

    if choice in ('1', '2', '3', '4', '5', '6', '7'):
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == '1':
            print(f"Result: {num1} + {num2} = {num1 + num2}")
        elif choice == '2':
            print(f"Result: {num1} - {num2} = {num1 - num2}")
        elif choice == '3':
            print(f"Result: {num1} * {num2} = {num1 * num2}")
        elif choice == '4':
            if num2 != 0:
                print(f"Result: {num1} / {num2} = {num1 / num2}")
            else:
                print("Error! Division by zero is not allowed.")
        elif choice == '5':
            print(f"Result: {num1} % {num2} = {num1 % num2}")
        elif choice == '6':
            print(f"Result: {num1} ** {num2} = {num1 ** num2}")
        elif choice == '7':
            if num2 != 0:
                print(f"Result: {num1} // {num2} = {num1 // num2}")
            else:
                print("Error! Division by zero is not allowed.")
    else:
        print("Invalid input. Please enter a valid option.")

# Run the calculator function
calculator()

Select operation:
1. Addition (+)
2. Subtraction (-)
3. Multiplication (*)
4. Division (/)
5. Modulus (%)
6. Exponentiation (**)
7. Floor Division (//)
Result: 34.0 - 23.0 = 11.0


In [4]:
#Activity_1(b)
# Modify the temperature converter program to include conversions between Celsius, Fahrenheit, and Kelvin.
def convert_temperature():
    while True:
        units = {'1': 'C', '2': 'F', '3': 'K'}
        print("\nConvert from: 1. Celsius  2. Fahrenheit  3. Kelvin  4. Quit")
        choice = input("Enter choice (1-3) or '4' to quit: ")

        if choice == '4':
            break
        if choice not in units:
            print("Invalid input. Try again.")
            continue

        temp = float(input(f"Enter temperature in {units[choice]}: "))
        c = temp if choice == '1' else (temp - 32) * 5/9 if choice == '2' else temp - 273.15
        f, k = (c * 9/5) + 32, c + 273.15
        print(f"{temp}{units[choice]} = {c:.2f}C = {f:.2f}F = {k:.2f}K")

convert_temperature()



Convert from: 1. Celsius  2. Fahrenheit  3. Kelvin  4. Quit
45.0F = 7.22C = 45.00F = 280.37K

Convert from: 1. Celsius  2. Fahrenheit  3. Kelvin  4. Quit
56.0K = -217.15C = -358.87F = 56.00K

Convert from: 1. Celsius  2. Fahrenheit  3. Kelvin  4. Quit


In [6]:
#Activity_01(c)
# Modify the program to allow the user to input five numbers and find the largest number among them.
def find_largest_number():
    numbers = [float(input(f"Enter number {i+1}: ")) for i in range(5)]
    print(f"The largest number is: {max(numbers)}")

find_largest_number()

The largest number is: 86.0


In [7]:
#Activity_02
# Modify the word count program to also count the frequency of each word in the sentence.
def word_count(sentence):
    words = sentence.split()
    word_freq = {word: words.count(word) for word in set(words)}
    return len(words), word_freq

sentence = input("Enter a sentence: ")
count, frequency = word_count(sentence)
print(f"Total words: {count}\nWord Frequency: {frequency}")

Total words: 5
Word Frequency: {'i': 1, 'am': 1, 'SHrestha': 1, 'Hello': 1, 'Riyan': 1}


In [18]:
#Activity_03(a)
# Write a program that performs additional operations on the list such as sorting and reversing the list, in addition to insert, delete, and find operations.
def list_operations():
    lst = [1, 2, 3, 4, 5]
    while True:
        print("\nChoose an operation:")
        print("1. Insert element")
        print("2. Delete element")
        print("3. Find element")
        print("4. Sort list")
        print("5. Reverse list")
        print("6. Exit")
        
        print(f"Current list: {lst}")
        choice = input("Enter choice (1-6): ")
        
        if choice == '1':
            try:
                element = int(input("Enter integer element to insert: "))
                lst.append(element)
                print(f"Inserted {element}. Updated list: {lst}")
            except ValueError:
                print("Invalid input! Please enter an integer.")
        elif choice == '2':
            try:
                element = int(input("Enter integer element to delete: "))
                if element in lst:
                    lst.remove(element)
                    print(f"Deleted {element}. Updated list: {lst}")
                else:
                    print("Element not found.")
            except ValueError:
                print("Invalid input! Please enter an integer.")
        elif choice == '3':
            try:
                element = int(input("Enter integer element to find: "))
                print("Element found" if element in lst else "Element not found")
            except ValueError:
                print("Invalid input! Please enter an integer.")
        elif choice == '4':
            lst.sort()
            print(f"List sorted: {lst}")
        elif choice == '5':
            lst.reverse()
            print(f"List reversed: {lst}")
        elif choice == '6':
            print("Exiting program. Goodbye!")
            break
        else:
            print("Invalid choice. Try again.")

list_operations()


Choose an operation:
1. Insert element
2. Delete element
3. Find element
4. Sort list
5. Reverse list
6. Exit
Current list: [1, 2, 3, 4, 5]
Deleted 3. Updated list: [1, 2, 4, 5]

Choose an operation:
1. Insert element
2. Delete element
3. Find element
4. Sort list
5. Reverse list
6. Exit
Current list: [1, 2, 4, 5]
Element not found.

Choose an operation:
1. Insert element
2. Delete element
3. Find element
4. Sort list
5. Reverse list
6. Exit
Current list: [1, 2, 4, 5]
Exiting program. Goodbye!


In [19]:
#Activity_03(b)
# Extend the dictionary merge program to handle cases where the two dictionaries have overlapping keys. If a key exists in both dictionaries, the merged dictionary should add the values of the overlapping keys.
def merge_dictionaries(dict1, dict2):
    merged_dict = dict1.copy()
    for key, value in dict2.items():
        if key in merged_dict:
            merged_dict[key] += value  
        else:
            merged_dict[key] = value
    return merged_dict

# Example usage
dict1 = {'a': 10, 'b': 20, 'c': 30}
dict2 = {'b': 5, 'c': 15, 'd': 40}
merged = merge_dictionaries(dict1, dict2)
print("Merged Dictionary:", merged)

Merged Dictionary: {'a': 10, 'b': 25, 'c': 45, 'd': 40}


In [21]:
#Activity_04(a)
import pandas as pd
df=pd.read_csv('1experience.csv')

print(f"1. Last 3 rows only\n{df.tail(3)}")
print("2. Description and information")
print(f"{df.describe()}")
print(df.info())

print(f"3. Column names {df.columns}")

1. Last 3 rows only
   YearsExperience
6              3.0
7              3.2
8              3.2
2. Description and information
       YearsExperience
count         9.000000
mean          2.266667
std           0.839643
min           1.100000
25%           1.500000
50%           2.200000
75%           3.000000
max           3.200000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  9 non-null      float64
dtypes: float64(1)
memory usage: 204.0 bytes
None
3. Column names Index(['YearsExperience'], dtype='object')


In [22]:
#Activity_06(a)
#Python program to create 3 X 3 Numpy array filled with random integer between 1 and 20, calculates the mean , and replaces all element less than 10 with 0
import numpy as np

array=np.random.randint(1,21, (3,3))
print("\nArray without the mean value : \n", array)
mean = np.mean(array)
print("\nArray with mean value : \n", mean)
array[array < 10 ] = 0
print("\nArray after replacing the value : \n ", array)


Array without the mean value : 
 [[13  6  8]
 [ 3 19 19]
 [19 12  8]]

Array with mean value : 
 11.88888888888889

Array after replacing the value : 
  [[13  0  0]
 [ 0 19 19]
 [19 12  0]]


In [23]:
#Activity_06(b)
#python program that creates 3 X 3 matrices between 1 and 10 . Perform amtrix suubtraction, element wise division , of both matrices
import numpy as np

matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)

sub = matrix1-matrix2
division= matrix1 / matrix2

print("\nMatrix Subtraction:\n", sub)
print("\nElement-wise Division:\n", division)

Matrix 1:
 [[5 3 7]
 [6 5 5]
 [2 5 7]]

Matrix 2:
 [[9 1 6]
 [3 4 8]
 [9 8 3]]

Matrix Subtraction:
 [[-4  2  1]
 [ 3  1 -3]
 [-7 -3  4]]

Element-wise Division:
 [[0.55555556 3.         1.16666667]
 [2.         1.25       0.625     ]
 [0.22222222 0.625      2.33333333]]


In [24]:
#Activity_07(a)
#create a pandas dataframe frome a list of dictionaries.The data represents information about prouducts 
#(Products Name, Category, and Price). Add a new column that calculates the discounted price (90% of the original price) and display the DataFrame
import pandas as pd
data= {
     'Products Name' : ['Face Wash', 'Soap', 'Gel'],
     'Category' : ['A', 'B', 'A'],
     'Price' : [200, 190, 250]
     }
df = pd.DataFrame(data,index=["i", "ii", "iii"])
print(df)
print()
df['Discounted Price'] = df['Price'] * 0.90
print(df)

    Products Name Category  Price
i       Face Wash        A    200
ii           Soap        B    190
iii           Gel        A    250

    Products Name Category  Price  Discounted Price
i       Face Wash        A    200             180.0
ii           Soap        B    190             171.0
iii           Gel        A    250             225.0


In [11]:
#Activity_07(b)
import pandas as pd
df=pd.read_csv('6Mcd_null_values.csv')
print(f"After filling all the null values : \n{df.fillna(0)}")
print(f"After dropping duplicates :\n{df.drop_duplicates()}")

After filling all the null values : 
    Year  McDonalds_Revenue_$Billion  Growth_rate_percent   Q1   Q2   Q3   Q4  \
0   1999                        13.3                  0.0  0.0  0.0  0.0  0.0   
1   2000                        14.2                  7.0  0.0  0.0  0.0  0.0   
2   2001                        14.9                  4.0  0.0  0.0  0.0  0.0   
3   2002                        15.4                  4.0  0.0  0.0  0.0  3.0   
4   2003                        17.1                 11.0  3.8  4.3  4.5  4.6   
5   2004                        18.6                  8.0  4.4  4.7  4.9  4.5   
6   2005                        19.1                  3.0  4.8  5.1  5.3  3.9   
7   2006                        20.9                  9.0  4.9  5.4  5.5  5.1   
8   2007                        22.8                  9.0  5.3  5.8  5.9  5.8   
9   2008                        23.5                  3.0  5.6  6.1  6.3  5.6   
10  2009                        22.7                 -3.0  5.1  5.6  6.0

In [9]:
#Activity_08
import pandas as pd
df=pd.read_csv('2salary.csv')

mean_value=df['Salary'].mean()
median_value=df['Salary'].median()
mode_value=df['Salary'].mode()[0]
min_value=df['Salary'].min()
max_value=df['Salary'].max()
variance_value=df['Salary'].var()
std_value=df['Salary'].std()

print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Mode: {mode_value}")
print(f"Minimum: {min_value}")
print(f"Maximum: {max_value}")
print(f"Variance: {variance_value}")
print(f"Standard Deviation: {std_value}")

Mean: 49153.0
Median: 46205.0
Mode: 37731
Minimum: 37731
Maximum: 64445
Variance: 98964696.75
Standard Deviation: 9948.100157819079


In [8]:
#Activity_09
import pandas as pd
df=pd.read_csv('2salary.csv')

description=df['Salary'].describe()
quantile=df['Salary'].quantile()
skewness=df['Salary'].skew()
kurtosis=df['Salary'].kurt()
value_count=df['Salary'].value_counts()

print(f"Statistical Summary : \n{description}")
print(f"Quantiles : {quantile}")
print(f"Skewness : {skewness}")
print(f"Kurtosis : {kurtosis}")
print(f"Value Counts : {value_count}")

Statistical Summary : 
count        9.000000
mean     49153.000000
std       9948.100158
min      37731.000000
25%      39891.000000
50%      46205.000000
75%      56642.000000
max      64445.000000
Name: Salary, dtype: float64
Quantiles : 46205.0
Skewness : 0.33325419097568093
Kurtosis : -1.6188766298502557
Value Counts : Salary
39343    1
46205    1
37731    1
43525    1
39891    1
56642    1
60150    1
54445    1
64445    1
Name: count, dtype: int64


In [17]:
#Activity_10
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv('4laptops.csv')
df['Storage'] = df[' Storage'].str.strip()

enc = OneHotEncoder()
encoded = enc.fit_transform(df[['Storage']]).toarray()
encoded_df = pd.DataFrame(encoded, columns=enc.get_feature_names_out(['Storage']))

df = pd.concat([df, encoded_df], axis=1)
print(df.head())


  Manufacturer   Model_Name   Category  Screen_size_inches  \
0        Apple  MacBook Pro  Ultrabook                13.3   
1        Apple  Macbook Air  Ultrabook                13.3   
2           HP       250 G6   Notebook                15.6   
3        Apple  MacBook Pro  Ultrabook                15.4   
4        Apple  MacBook Pro  Ultrabook                13.3   

                               Screen                         CPU   RAM  \
0  IPS Panel Retina Display 2560x1600        Intel Core i5 2.3GHz   8GB   
1                            1440x900        Intel Core i5 1.8GHz   8GB   
2                   Full HD 1920x1080  Intel Core i5 7200U 2.5GHz   8GB   
3  IPS Panel Retina Display 2880x1800        Intel Core i7 2.7GHz  16GB   
4  IPS Panel Retina Display 2560x1600        Intel Core i5 3.1GHz   8GB   

               Storage                           GPU Operating_System  ...  \
0            128GB SSD  Intel Iris Plus Graphics 640            macOS  ...   
1  128GB Flash Stora

In [25]:
#Activity_11
import pandas as pd

#Using Normalizer
df=pd.read_csv('3Salary_Data.csv')

from sklearn.preprocessing import Normalizer

normalizer=Normalizer()
normalized_data=normalizer.fit_transform(df)
normalized_df1=pd.DataFrame(normalized_data,columns=df.columns)
normalized_df1

#Using MinMaxScaler
df=pd.read_csv('3Salary_Data.csv')

from sklearn.preprocessing import MinMaxScaler

minmaxscaler=MinMaxScaler()
minmaxscaled_data=minmaxscaler.fit_transform(df)
minmaxscaled_df1=pd.DataFrame(minmaxscaled_data,columns=df.columns)
minmaxscaled_df1

YearsExperience    Salary
0          0.000000  0.019041
1          0.021277  0.100094
2          0.042553  0.000000
3          0.095745  0.068438
4          0.117021  0.025514
5          0.191489  0.223376
6          0.202128  0.264812
7          0.223404  0.197425
8          0.223404  0.315545
9          0.276596  0.229837
10         0.297872  0.301051
11         0.308511  0.213359
12         0.308511  0.227097
13         0.319149  0.228561
14         0.361702  0.276163
15         0.404255  0.356804
16         0.425532  0.334255
17         0.446809  0.535755
18         0.510638  0.515379
19         0.521277  0.663938
20         0.606383  0.637928
21         0.638298  0.715119
22         0.723404  0.750898
23         0.755319  0.898665
24         0.808511  0.846917
25         0.840426  0.801453
26         0.893617  0.935956
27         0.904255  0.884763
28         0.978723  1.000000
29         1.000000  0.993870